version: "3"
services:
  db:
    image: mysql:5.7.19
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    environment:
      DATABASE_URL: mysql2://root:password@db:3306
    volumes:
      - .:/hondana_space
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle:
