development: &default
  adapter: mysql2
  database: hondana_space_development
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  database: hondana_space_test

production:
  <<: *default
